AWSTemplateFormatVersion: 2010-09-09
Description: Basic S3 bucket enabled with access from this account and Ops.
Parameters:
  BucketName:
    Description: >-
      Name of the S3 bucket to create, this should be unique and lowercase. Will
      be prefixed by tom- and suffixed by the environment code.
    Type: String
    Default: ''
  Division:
    Description: The division that will be consuming/is provisioning this service.
    Type: String
    AllowedValues:
      - Core
      - Arcade
      - xxxx
      - International
  Team:
    Description: The team that will be primarily consuming/is provisioning this service.
    Type: String
    AllowedValues:
      - Client
      - Engine
      - Platform
      - ISA
      - Infra
      - Data Engineering
  Role:
    Description: The role this service will be helping to complete.
    Type: String
    AllowedValues:
      - Build and Deployment
      - Chat
      - Data
      - DB
      - Game
      - Infrastructure
      - Reporting
      - Testing
      - VPN
      - Web
      - Website Misc
  Country:
    Description: >-
      The country that will be primarily consuming/is provisioning this service
      or EU for all.
    Type: String
    AllowedValues:
      - ES
      - EU
      - IT
      - PT
      - UK
  ChangeNo:
    Description: >-
      A change number or JIRA ticket that records the authorisation for the
      stack to be built or the feature request this stack is part of.
    Type: String
Metadata:
  ProductName: Basic S3 Bucket
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Bucket Settings
        Parameters:
          - BucketName
      - Label:
          default: Misc Details
        Parameters:
          - Division
          - Team
          - Role
          - Country
          - ChangeNo
    ParameterLabels:
      BucketName:
        default: Bucket Name
      ChangeNo:
        default: Change Number
Mappings:
  EnvironmentCodeToLowerCase:
    PR:
      Value: pr
    DV:
      Value: dv
    ST:
      Value: st
    PLY:
      Value: ply
    OPG:
      Value: opg
  AccountVariables:
    'xxxxxxx':
      Environment: INFRA
      EnvironmentCode: PR
      OctopusEnvironment: DeployToEMEA
      VpcId: vpc-xxxxx
      PrivateSubnetA: subnet-xxx
      PrivateSubnetB: subnet-xxx
      PublicSubnetA: subnet-xxx
      PublicSubnetB: subnet-xxx
      AdminSecurityGroup: sg-xxxxx
    '07545889xxxxx':
      Environment: DEV
      EnvironmentCode: DV
      OctopusEnvironment: DeployToDev
      VpcId: vpc-xxxxx
      PrivateSubnetA: subnet-xxx
      PrivateSubnetB: subnet-xxx
      PublicSubnetA: subnet-xxx
      PublicSubnetB: subnet-xxx
      AdminSecurityGroup: sg-xxxxx
    '094345xxxx':
      Environment: STAGE
      EnvironmentCode: ST
      OctopusEnvironment: DeployToStaging
      VpcId: vpc-xxxxx
      PrivateSubnetA: subnet-xxx
      PrivateSubnetB: subnet-xxx
      PublicSubnetA: subnet-xxx
      PublicSubnetB: subnet-xxx
      AdminSecurityGroup: sg-xxxxx
    '189470x':
      Environment: LIVE
      EnvironmentCode: PR
      OctopusEnvironment: DeployToLive
      VpcId: vpc-xxxxx
      PrivateSubnetA: subnet-xxx
      PrivateSubnetB: subnet-xxx
      PublicSubnetA: subnet-xxx
      PublicSubnetB: subnet-xxx
      AdminSecurityGroup: sg-xxxxx    
Resources:
  BUCKET:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Join
        - '-'
        - - tom
          - !Ref BucketName
          - !FindInMap
            - EnvironmentCodeToLowerCase
            - !FindInMap
              - AccountVariables
              - !Ref 'AWS::AccountId'
              - EnvironmentCode
            - Value
      Tags:
        - Key: Country
          Value: !Ref Country
        - Key: Environment
          Value: !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - Environment
        - Key: Division
          Value: !Ref Division
        - Key: Team-Role
          Value: !Join
            - '-'
            - - !Ref Team
              - !Ref Role
        - Key: Source
          Value: Service Catalog
      VersioningConfiguration:
        Status: Suspended
  BUCKETPOLICY:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref BUCKET
      PolicyDocument:
        Statement:
          - Sid: Allow Ops Access
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::xxxxxxx:root'
            Action:
              - 's3:List*'
              - 's3:Get*'
              - 's3:Delete*'
              - 's3:Put*'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BUCKET
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BUCKET
                  - /*
          - Sid: Allow Local Access
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action:
              - 's3:List*'
              - 's3:Get*'
              - 's3:Delete*'
              - 's3:Put*'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BUCKET
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BUCKET
                  - /*
Outputs:
  BUCKET:
    Description: The Bucket name.
    Value: !Ref BUCKET
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - BUCKET
  BUCKETDomainName:
    Description: The Domain Name for the Bucket.
    Value: !GetAtt
      - BUCKET
      - DomainName
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - BUCKETDomainName
Rules: {}
