---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to launch ECS cluster with public ALB and single
  listener and target group
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  ClusterName:
    Type: String
    Description: Name of to give the cluster.
    Default: EUECS
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC that allows instances to access the Internet.
  ALBSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-dae3bex
    Description: The Subnets where the ALB will be launched
  InstanceSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-dae3bx
    Description: The Subnets where the Cluster Instances will be launched
  AMI:
    Description: AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-xxx
  DesiredCapacity:
    Type: Number
    Default: '1'
    Description: Number of instances to launch in your ECS cluster.
  MinSize:
    Type: Number
    Default: '1'
    Description: Minimum number of instances that can be launched in your ECS cluster.
  MaxSize:
    Type: Number
    Default: '2'
    Description: Maximum number of instances that can be launched in your ECS cluster.
  AdminSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-02298xx
    Description: The administrative security group for this cluster
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m4.large
    - c4.large
    - r4.large
    ConstraintDescription: Please choose a valid instance type.
  Environment:
    Type: String
    Default: DEV
    AllowedValues:
    - PLAY
    - DEV
    - STAGE
    - LIVE
  SSLCertificate:
    Description: SSL Certificate to be used on External ALB
    Type: String
    AllowedValues:
    - wildcard-xxxx-com
    - wildcard-xxxx-uk
    - wildcard-xxxx-it
    - wildcard-xxxx-es
    - wildcard-arcade-uk
    Default: wildcard-xxxx-com
Mappings:
  EnvironmentToCode:
    PLAY:
      Value: PY
    DEV:
      Value: DV
    STAGE:
      Value: ST
    LIVE:
      Value: PR
  SSLCertificateToCode:
    wildcard-xxxx-uk:
      INFRA: arn:aws:acm:eu-west-1:xxx:certificate/f12bfaf4-2354-46ed-87a9-fb07c117b769
      PLAY: arn:aws:acm:eu-west-1:xxx:certificate/6bab9d4a-a7b6-4dab-b3b3-303c7a3390de
      DEV: arn:aws:acm:eu-west-1:xxx:certificate/1a347d01-e41f-41ca-963d-a1b8279fe0de
      STAGE: arn:aws:acm:eu-west-1:xxx:certificate/ea14c595-1bdd-4037-98c4-0d5dd65d3313
      LIVE: arn:aws:acm:eu-west-1:xxx:certificate/378f64a7-c347-4e80-b068-7c99b1dfb4f9
    wildcard-xxxx-it:
      INFRA: arn:aws:acm:eu-west-1:xxx:certificate/dbc84553-7245-4d36-97f9-8458f2dfc2cf
      PLAY: arn:aws:acm:eu-west-1:xxx:certificate/1a503a35-2e8a-4c10-a4d5-1299e655398b
      DEV: arn:aws:acm:eu-west-1:xxx:certificate/bdb2a7a2-a9d7-4a29-93c0-56917b6bf208
      STAGE: arn:aws:acm:eu-west-1:xxx:certificate/b943fe91-954b-4bf8-814e-5230011f634b
      LIVE: arn:aws:acm:eu-west-1:xxx:certificate/72054d5e-3e8c-4eb5-9a65-e101dd07fa58
    wildcard-xxxx-es:
      INFRA: arn:aws:acm:eu-west-1:xxx:certificate/d8f99f82-d7ab-45bd-981f-567c2abb1f5d
      PLAY: arn:aws:acm:eu-west-1:xxx:certificate/2e4ffa43-da25-4dc1-bdb7-c22780355662
      DEV: arn:aws:acm:eu-west-1:xxx:certificate/8570651c-4141-49ee-8250-8972660d08a5
      STAGE: arn:aws:acm:eu-west-1:xxx:certificate/1bbd90ad-3b86-4f4e-99a4-3befe13819c1
      LIVE: arn:aws:acm:eu-west-1:xxx:certificate/feef62fb-6cac-4c4f-97f4-adde1d01ff7b
    wildcard-xxxx-pt:
      INFRA: arn:aws:acm:eu-west-1:xxx:certificate/54251bb7-2db6-4bf0-a5ef-7924498820c1
      PLAY: arn:aws:acm:eu-west-1:xxx:certificate/278e06a5-b5d0-4e5e-b6ed-6a2dab0c8047
      DEV: arn:aws:acm:eu-west-1:xxx:certificate/bf85c614-5763-43a3-b332-d0f8e07deb88
      STAGE: arn:aws:acm:eu-west-1:xxx:certificate/ec05f804-621f-41e3-963f-a15649907f45
      LIVE: arn:aws:acm:eu-west-1:xxx:certificate/b1a134e4-ae13-40c0-857e-72bcce4bc7fc
    wildcard-xxxx-com:
      INFRA: arn:aws:acm:eu-west-1:xxx:certificate/b8eecc28-bfca-4e58-a8b8-8c89b4653a45
      PLAY: arn:aws:acm:eu-west-1:xxx:certificate/eadafb9e-a9be-440c-b689-8ed87e613902
      DEV: arn:aws:acm:eu-west-1:xxx:certificate/5ea6c86b-eff9-454d-acbe-811e866ea890
      STAGE: arn:aws:acm:eu-west-1:xxx:certificate/88c64072-8976-41af-9b49-092c370f7033
      LIVE: arn:aws:acm:eu-west-1:xxx:certificate/182dae2f-6d7f-4d9d-b633-5175a14949b8
    wildcard-arcade-uk:
      INFRA: arn:aws:acm:eu-west-1:xxx:certificate/b16e9141-7263-4c4c-93fc-66d96f7f2a64
      PLAY: arn:aws:acm:eu-west-1:xxx:certificate/86b4b2be-b208-4c87-89b9-c79d47efce95
      DEV: arn:aws:acm:eu-west-1:xxx:certificate/c5295396-0a74-4bd4-a752-b34fe4deb91e
      STAGE: arn:aws:acm:eu-west-1:xxx:certificate/67f1bcf6-a1d4-45a8-878c-aeec8a3d066a
      LIVE: arn:aws:acm:eu-west-1:xxx:certificate/b76b8ab1-8bc5-47d9-9a24-ca50e5d332a4
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName:
        Fn::Join:
        - ''
        - - Ref: ClusterName
          - C
          - Fn::FindInMap:
            - EnvironmentToCode
            - Ref: Environment
            - Value
  ExternalALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId:
        Ref: VpcId
  ExternalALBSecurityGroupHTTPSinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: ExternalALBSecurityGroup
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      CidrIp: 0.0.0.0/0
  ExternalECSALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn:
    - ExternalALBSecurityGroup
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '30'
      Subnets:
        Ref: ALBSubnets
      SecurityGroups:
      - Ref: ExternalALBSecurityGroup
      - Ref: AdminSecurityGroup
      Tags:
      - Key: Team-Role
        Value: Platform-Web Misc
      - Key: Division
        Value: Core
      - Key: Country
        Value: EU
      - Key: Environment
        Value:
          Ref: Environment
  ExternalALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ECSTG
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: ECSTG
      LoadBalancerArn:
        Ref: ExternalECSALB
      Port: '443'
      Protocol: HTTPS
      Certificates:
      - CertificateArn:
          Fn::FindInMap:
          - SSLCertificateToCode
          - Ref: SSLCertificate
          - Ref: Environment
  ECSTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ExternalECSALB
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: "/"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name:
        Fn::Join:
        - ''
        - - ECSTG-
          - Ref: ClusterName
      Port: 443
      Protocol: HTTPS
      UnhealthyThresholdCount: 5
      VpcId:
        Ref: VpcId
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        Ref: InstanceSubnets
      LaunchConfigurationName:
        Ref: ContainerInstances
      MinSize:
        Ref: MinSize
      MaxSize:
        Ref: MaxSize
      DesiredCapacity:
        Ref: DesiredCapacity
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - Ref: ClusterName
            - C
            - Fn::FindInMap:
              - EnvironmentToCode
              - Ref: Environment
              - Value
        PropagateAtLaunch: 'true'
      - Key: Team-Role
        Value: Platform-Website Misc
        PropagateAtLaunch: 'true'
      - Key: Division
        Value: Core
        PropagateAtLaunch: 'true'
      - Key: Country
        Value: EU
        PropagateAtLaunch: 'true'
      - Key: Environment
        Value:
          Ref: Environment
        PropagateAtLaunch: 'true'
      - Key: AMI
        Value:
          Ref: AMI
        PropagateAtLaunch: 'true'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 2
        PauseTime: PT5M
  ClusterScaleUp:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: ECSAutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: 1
  ClusterScaleDown:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: ECSAutoScalingGroup
      Cooldown: 600
      ScalingAdjustment: -1
  ClusterCPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU > 70% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '70'
      AlarmActions:
      - Ref: ClusterScaleUp
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: ECSAutoScalingGroup
      ComparisonOperator: GreaterThanThreshold
  ClusterCPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU < 10% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '600'
      EvaluationPeriods: '1'
      Threshold: '10'
      AlarmActions:
      - Ref: ClusterScaleDown
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: ECSAutoScalingGroup
      ComparisonOperator: LessThanThreshold
  ContainerInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: aws-ecs-ec2-role
      ImageId:
        Ref: AMI
      SecurityGroups:
      - Ref: AdminSecurityGroup
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
            - echo ECS_CLUSTER=
            - Ref: ECSCluster
            - " >> /etc/ecs/ecs.config\n"
            - 'yum install -y aws-cfn-bootstrap

'
            - "/opt/aws/bin/cfn-signal -e $? "
            - "         --stack "
            - Ref: AWS::StackName
            - "         --resource ECSAutoScalingGroup "
            - "         --region "
            - Ref: AWS::Region
            - "\n"
