AWSTemplateFormatVersion: 2010-09-09
Description: A basic CloudFormation template for an RDS Aurora cluster.
Parameters:
  DatabaseInstanceType:
    Description: The instance type to use for the database.
    Type: String
    Default: db.t2.medium
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.m3.large
      - db.m3.xlarge
      - db.m3.2xlarge
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    ConstraintDescription: Must select a valid database instance type.
  DatabaseInstanceName:
    Default: amysql
    Description: The database name
    Type: String
    MinLength: '6'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DatabaseUsername:
    Default: sqldba
    Description: The database admin account username
    Type: String
    MinLength: '6'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DatabasePassword:
    Default: Password
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DatabaseBackupRetentionPeriod:
    Type: String
    Default: '7'
    AllowedValues:
      - '1'
      - '7'
    Description: The database backup retention period in days.
  Division:
    Description: The division that will be consuming/is provisioning this service.
    Type: String
    AllowedValues:
      - Core
      - Arcade
      - Bingo
      - International
  Team:
    Description: The team that will be primarily consuming/is provisioning this service.
    Type: String
    AllowedValues:
      - Client
      - Engine
      - Platform
      - ISA
      - Infra
      - Data Engineering
  Role:
    Description: The role this service will be helping to complete.
    Type: String
    AllowedValues:
      - Build and Deployment
      - Chat
      - Data
      - DB
      - Game
      - Infrastructure
      - Reporting
      - Testing
      - VPN
      - Web
      - Website Misc
  Country:
    Description: >-
      The country that will be primarily consuming/is provisioning this service
      or EU for all.
    Type: String
    AllowedValues:
      - DK
      - ES
      - EU
      - IT
      - NL
      - PT
      - UK
  ChangeNo:
    Description: >-
      A change number or JIRA ticket that records the authorisation for the
      stack to be built or the feature request this stack is part of.
    Type: String
Metadata:
  ProductName: Standard Aurora Build
  'AWS::CloudFormation::Interface:':
    ParameterGroups:
      - Label:
          default: Database Configuration
        Parameters:
          - DatabaseInstanceType
          - DatabaseInstanceName
          - DatabaseUsername
          - DatabasePassword
          - DatabaseBackupRetentionPeriod
      - Label:
          default: Misc Details
        Parameters:
          - Division
          - Team
          - Role
          - Country
          - ChangeNo
    ParameterLabels:
      DatabaseInstanceType:
        default: Instance Type
      DatabaseInstanceName:
        default: Instance Name
      DatabaseUsername:
        default: Database Username
      DatabasePassword:
        default: SqlDBA Password
      DatabaseBackupRetentionPeriod:
        default: Database Backup Retention Period
      ChangeNo:
        default: Change Number
Mappings:
  AccountVariables:
    '1608211xxxxx':
      Environment: INFRA
      EnvironmentCode: PR
      OctopusEnvironment: DeployToEMEA
      VpcId: vpc-xxxx
      PrivateSubnetA: subnet-bc2d1xxx
      PrivateSubnetB: subnet-bc2d1xxx
      PublicSubnetA: subnet-bc2d1xxx
      PublicSubnetB: subnet-bc2d1xxx
      AdminSecurityGroup: sg-xxxx
    075458x4:
      Environment: DEV
      EnvironmentCode: DV
      VpcId: vpc-70226x
      PrivateSubnetA: subnet-7018x
      PrivateSubnetB: subnet-4ebfcx
      PublicSubnetA: subnet-711841x
      PublicSubnetB: subnet-41bfcex
      AdminSecurityGroup: sg-29d16x
    09434501x:
      Environment: STAGE
      EnvironmentCode: ST
      VpcId: vpc-3bace55e
      PrivateSubnetA: subnet-9f227x
      PrivateSubnetB: subnet-edfb8x
      PublicSubnetA: subnet-902279ex
      PublicSubnetB: subnet-e98efx
      AdminSecurityGroup: sg-ee7cx
    '18947079x':
      Environment: LIVE
      EnvironmentCode: PR
      VpcId: vpc-2aea4x
      PrivateSubnetA: subnet-2a3a1x
      PrivateSubnetB: subnet-3796cx
      PublicSubnetA: subnet-066a266x
      PublicSubnetB: subnet-1ea428x
      AdminSecurityGroup: sg-1c30ax
    '63070211x':
      Environment: PLAY
      EnvironmentCode: PLY
      VpcId: vpc-1353x
      PrivateSubnetA: subnet-83cffx
      PrivateSubnetB: subnet-f36d919x
      AdminSecurityGroup: sg-6541x
    '84335267x':
      Environment: OPS-PLAY
      EnvironmentCode: PLY
      VpcId: vpc-b35ee0d4
      PrivateSubnetA: subnet-ex
      PrivateSubnetB: subnet-4ebfcx
      AdminSecurityGroup: sg-9c8x
  SecurityGroups:
    '1608211xxxxx':
      ADMIN: sg-xxxx
      ALIENV: sg-42b6fx
      CHATLOG: sg-95b8f8x
      DC: sg-52b8f8xx
      EPO: sg-e3b9fxa
      OD: sg-cebcfcx
      OPSBLOG: sg-0ebax
      PLAYG: sg-05b7f7x
      PMP: sg-fab8f88x
      PRTG: sg-7cbafax
      RDS: sg-7fb7f70x
      SOGEI: sg-989cd6e1x
      TC: sg-89bbfbf0x
      VPN: sg-6b93d912x
      WEB: sg-a8b7f7d1x
    075458894x:
      ADMIN: sg-29d16x
      APP: sg-d1eb5fx8
      CHAT: sg-aed76x7
      CMS: sg-de255ax
      DC: sg-36d165xf
      GAME: sg-2bd662x
      JS: sg-29d662x
      LOGAPI: sg-59d7x
      NAT: sg-48d06431
      NOSQL: sg-05d2667c
      PROXY: sg-f6d5618f
      RDS: sg-deeb5fa7
      REDIS: sg-17d7636e
      SOGEI: sg-fa174183
      WEBRES: sg-8fd561f6
      WEB: sg-76d4600f
    094345010951:
      ADMIN: sg-ee7cf097
      APP: sg-2861ed51
      CHAT: sg-627ef21b
      CMS: sg-c52f50bc
      DC: sg-2b61ed52
      JS: sg-6b60ec12
      GAME: sg-e661ed9f
      LOGAPI: sg-6a60ec13
      NAT: sg-aa63efd3
      NOSQL: sg-8361edfa
      PROXY: sg-4c66ea35
      RDS: sg-c37df1ba
      REDIS: sg-e17cf098
      SOGEI: sg-f3cfb38a
      WEBRES: sg-e761ed9e
      WEB: sg-0160ec78
      WHOS: sg-21fe8958
    '189470795347':
      ADMIN: sg-1c30aa65
      APP: sg-862bb1ff
      CHAT: sg-1d30aa64
      CMS: sg-842bb1fd
      DC: sg-a337adda
      GAME: sg-9631abef
      JS: sg-622ab01b
      LOGAPI: sg-4d31ab34
      NAT: sg-a42ab0dd
      NOSQL: sg-8a34aef3
      PROXY: sg-bb28b2c2
      RDS: sg-4c31ab35
      REDIS: sg-a037add9
      SOGEI: sg-1e30aa67
      WEBRES: sg-c435afbd
      WEB: sg-da31aba3
      WHOS: sg-6337ad1a
    '630702119774':
      ADMIN: sg-65413d1c
      APP: sg-65413d1c
      CHAT: sg-65413d1c
      CMS: sg-65413d1c
      DC: sg-65413d1c
      GAME: sg-65413d1c
      JS: sg-65413d1c
      LOGAPI: sg-65413d1c
      NAT: sg-65413d1c
      NOSQL: sg-65413d1c
      PROXY: sg-65413d1c
      RDS: sg-65413d1c
      REDIS: sg-65413d1c
      SOGEI: sg-65413d1c
      WEBRES: sg-65413d1c
      WEB: sg-65413d1c
      WHOS: sg-65413d1c
    '843352679768':
      ADMIN: sg-9c8234e4
      APP: sg-ee843296
      CHAT: sg-848335fc
      CMS: sg-1a853362
      DC: sg-b88533c0
      GAME: sg-4f8e3837
      JS: sg-8d8432f5
      LOGAPI: sg-6682341e
      NAT: sg-2380365b
      NOSQL: sg-6582341d
      PROXY: sg-0782347f
      RDS: sg-eb8e3893
      REDIS: sg-e0833598
      SOGEI: sg-ed843295
      WEBRES: sg-ea8e3892
      WEB: sg-2480365c
Resources:
  DatabaseSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: CloudFormation managed DB subnet group.
      SubnetIds:
        - !FindInMap
          - AccountVariables
          - !Ref 'AWS::AccountId'
          - PrivateSubnetA
        - !FindInMap
          - AccountVariables
          - !Ref 'AWS::AccountId'
          - PrivateSubnetB
  DatabaseCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: aurora
      DatabaseName: !Join
        - ''
        - - !Ref Country
          - !Ref DatabaseInstanceName
          - c
          - !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - EnvironmentCode
          - '01'
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
      BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
      PreferredBackupWindow: '02:00-03:00'
      PreferredMaintenanceWindow: 'mon:03:00-mon:04:00'
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VpcSecurityGroupIds:
        - !FindInMap
          - AccountVariables
          - !Ref 'AWS::AccountId'
          - AdminSecurityGroup
        - !FindInMap
          - SecurityGroups
          - !Ref 'AWS::AccountId'
          - RDS
      Tags:
        - Key: Country
          Value: !Ref Country
        - Key: Environment
          Value: !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - Environment
        - Key: Division
          Value: !Ref Division
        - Key: Team-Role
          Value: !Join
            - '-'
            - - !Ref Team
              - !Ref Role
        - Key: Source
          Value: Service Catalog
  DatabasePrimaryInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora
      DBInstanceIdentifier: !Join
        - ''
        - - !Ref Country
          - !Ref DatabaseInstanceName
          - c
          - !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - EnvironmentCode
          - '01'
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: !Ref DatabaseInstanceType
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref Country
              - !Ref DatabaseInstanceName
              - c
              - !FindInMap
                - AccountVariables
                - !Ref 'AWS::AccountId'
                - EnvironmentCode
              - '01'
        - Key: Country
          Value: !Ref Country
        - Key: Environment
          Value: !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - Environment
        - Key: Division
          Value: !Ref Division
        - Key: Team-Role
          Value: !Join
            - '-'
            - - !Ref Team
              - !Ref Role
        - Key: Source
          Value: Service Catalog
  DatabaseReplicaInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora
      DBInstanceIdentifier: !Join
        - ''
        - - !Ref Country
          - !Ref DatabaseInstanceName
          - c
          - !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - EnvironmentCode
          - '02'
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: !Ref DatabaseInstanceType
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref Country
              - !Ref DatabaseInstanceName
              - c
              - !FindInMap
                - AccountVariables
                - !Ref 'AWS::AccountId'
                - EnvironmentCode
              - '02'
        - Key: Country
          Value: !Ref Country
        - Key: Environment
          Value: !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - Environment
        - Key: Division
          Value: !Ref Division
        - Key: Team-Role
          Value: !Join
            - '-'
            - - !Ref Team
              - !Ref Role
        - Key: Source
          Value: Service Catalog
Rules: {}
