AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Standard RDS server environment, running either Aurora, MySQL, MariaDB,
  PostgreSQL or MSSQL.
Parameters:
  InstanceName:
    Type: String
    Description: >-
      A descriptive name to give the instances, e.g. WEB. This will be prefixed
      by the Country and suffixed by the Environment automatically.
  InstanceType:
    Description: Type of RDS instance to launch.
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.m1.small
      - db.m3.medium
      - db.m3.large
      - db.m3.xlarge
      - db.m3.2xlarge
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
    ConstraintDescription: Must be a valid RDS instance type.
  Engine:
    Description: Type of RDS Engine
    Type: String
    AllowedValues:
      - MySQL
      - MariaDB
      - PostgreSQL
      - MSSQL-Express
      - MSSQL-Web
      - MSSQL-Standard
    ConstraintDescription: Must be a valid RDS instance type.
  AllocatedStorage:
    Type: String
    Default: '200'
    Description: Amount of storage in GB's to be allocated to instance.
  AdministratorPassword:
    NoEcho: 'true'
    Description: Master password for RDS instance.
    Type: String
    MinLength: 8
  Division:
    Description: The division that will be consuming/is provisioning this service.
    Type: String
    AllowedValues:
      - Core
      - Arcade
      - Bingo
      - International
  Team:
    Description: The team that will be primarily consuming/is provisioning this service.
    Type: String
    AllowedValues:
      - Client
      - Engine
      - Platform
      - ISA
      - Infra
      - Data Engineering
  Role:
    Description: The role this service will be helping to complete.
    Type: String
    AllowedValues:
      - Build
      - Chat
      - Data
      - DB
      - Game
      - Infrastructure
      - Reporting
      - Testing
      - VPN
      - Web
      - Misc
  Country:
    Description: >-
      The country that will be primarily consuming/is provisioning this service
      or EU for all.
    Type: String
    AllowedValues:
      - DK
      - ES
      - EU
      - IT
      - NL
      - PT
      - UK
  ChangeNo:
    Description: >-
      A change number or JIRA ticket that records the authorisation for the
      stack to be built or the feature request this stack is part of.
    Type: String
Metadata:
  ProductName: Standard RDS Instance
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Instance Settings
        Parameters:
          - InstanceName
          - Engine
          - InstanceType
          - AllocatedStorage
          - AdministratorPassword
      - Label:
          default: Misc Details
        Parameters:
          - Division
          - Team
          - Role
          - Country
          - ChangeNo
    ParameterLabels:
      InstanceName:
        default: Instance Name
      InstanceType:
        default: Instance Type
      AdministratorPassword:
        default: SqlDBA Password
      AllocatedStorage:
        default: Storage (GB)
      ChangeNo:
        default: Change Number
Mappings:
  EngineToEngineType:
    Aurora:
      EngineVersion: 5.6.10a
      EngineType: aurora
      License: general-public-license
    MySQL:
      EngineVersion: 5.7.11
      EngineType: mysql
      License: general-public-license
    MariaDB:
      EngineVersion: 10.1.14
      EngineType: mariadb
      License: general-public-license
    PostgreSQL:
      EngineVersion: 9.6.1
      EngineType: postgres
      License: general-public-license
    MSSQL-Express:
      EngineVersion: 12.00.5000.0.v1
      EngineType: sqlserver-ex
      License: license-included
    MSSQL-Web:
      EngineVersion: 12.00.5000.0.v1
      EngineType: sqlserver-web
      License: license-included
    MSSQL-Standard:
      EngineVersion: 12.00.5000.0.v1
      EngineType: sqlserver-se
      License: license-included
    MSSQL-Enterprise:
      EngineVersion: 12.00.5000.0.v1
      EngineType: sqlserver-ee
      License: license-included
  AccountVariables:
    '16082114xxx':
      Environment: INFRA
      EnvironmentCode: PR
      OctopusEnvironment: DeployToEMEA
      VpcId: vpc-e7d1xxx
      PrivateSubnetA: subnet-bc2d1xx
      PrivateSubnetB: subnet-bc2d1xx
      PublicSubnetA: subnet-bc2d1xx
      PublicSubnetB: subnet-bc2d1xx
      AdminSecurityGroup: sg-xxx
    075458894xx4:
      Environment: DEV
      EnvironmentCode: DV
      OctopusEnvironment: DeployToDev
      VpcId: vpc-70226x
      PrivateSubnetA: subnet-7018x
      PrivateSubnetB: subnet-4ebfx
      PublicSubnetA: subnet-71184x
      PublicSubnetB: subnet-41bfx
      AdminSecurityGroup: sg-29d1x
    09434501xxx:
      Environment: STAGE
      EnvironmentCode: ST
      OctopusEnvironment: DeployToStaging
      VpcId: vpc-3bacx
      PrivateSubnetA: subnet-9f22x
      PrivateSubnetB: subnet-edfbx
      PublicSubnetA: subnet-9022x
      PublicSubnetB: subnet-e98efx
      AdminSecurityGroup: sg-ee7cfxx
    '189470795xxx':
      Environment: LIVE
      EnvironmentCode: PR
      OctopusEnvironment: DeployToLive
      VpcId: vpc-2aea414f
      PrivateSubnetA: subnet-2a3x
      PrivateSubnetB: subnet-3796x
      PublicSubnetA: subnet-0xxa2x
      PublicSubnetB: subnet-1ea4x
      AdminSecurityGroup: sg-1c30xx
    '6307021xxx':
      Environment: PLAY
      EnvironmentCode: PLY
      OctopusEnvironment: DeployToPreDev
      VpcId: vpc-1353a174
      PrivateSubnetA: subnet-83cx
      PrivateSubnetB: subnet-f36x
      PublicSubnetA: subnet-64c3x
      PublicSubnetB: subnet-4b728xc
      AdminSecurityGroup: sg-6541xx
    '843352xxxx':
      Environment: OPSPLAY
      EnvironmentCode: OPG
      OctopusEnvironment: OpsPlayground
      VpcId: vpc-b35ee0d4
      PrivateSubnetA: subnet-e1d16x
      PrivateSubnetB: subnet-4ebx
      PublicSubnetA: subnet-74d4x
      PublicSubnetB: subnet-6cbx
      AdminSecurityGroup: sg-9c823xx
  SecurityGroups:
    '16082114xxx':
      ADMIN: sg-xxx
      ALIENV: sg-42b6fx
      CHATLOG: sg-95b8x
      DC: sg-52b8fx
      EPO: sg-e3b9x
      OD: sg-cebcfx
      OPSBLOG: sg-0ebax
      PLAYG: sg-05b7x
      PMP: sg-fab8fx
      PRTG: sg-7cbafx
      RDS: sg-7fb7fx
      SOGEI: sg-989cdx
      TC: sg-89bbfx
      VPN: sg-6b93dx
      WEB: sg-a8b7fxx
    075458894xx4:
      ADMIN: sg-29d1x
      APP: sg-d1ebx
      CHAT: sg-aed76x
      CMS: sg-de255x
      DC: sg-36d1654xx
      GAME: sg-2bdxx
      JS: sg-29dxx2x
      LOGAPI: sg-59d7x
      NAT: sg-48d0x
      NOSQL: sg-05d2xx
      PROXY: sg-f6d561x
      RDS: sg-deeb5fx
      REDIS: sg-17d763x
      SOGEI: sg-fa174x
      WEBRES: sg-8fd56x
      WEB: sg-76d460x
    09434501xxx:
      ADMIN: sg-ee7cx7
      APP: sg-2861x
      CHAT: sg-627x
      CMS: sg-c52x
      DC: sg-2b61x
      JS: sg-6b60x
      GAME: sg-exxx
      LOGAPI: sg-6a60ex
      NAT: sg-aa63ex
      NOSQL: sg-8361ex
      RDS: sg-c37dx
      REDIS: sg-e17x8
      SOGEI: sg-f3cfx
      WEBRES: sg-e761edxe
      WEB: sg-0160ecx
      WHOS: sg-21fe8x
    '189470795xxx':
      ADMIN: sg-1c30x
      APP: sg-862bx
      CHAT: sg-1d30x
      CMS: sg-842bx
      DC: sg-a337x
      GAME: sg-963x
      JS: sg-622abx
      LOGAPI: sg-4d3x
      NAT: sg-a42ab0dx
      NOSQL: sg-8a34axf3
      PROXY: sg-bb28x
      RDS: sg-4c31ax
      REDIS: sg-a0x
      SOGEI: sg-1e30aa6x
      WEBRES: sg-c435afbxd
      WEB: sg-da31abx
      WHOS: sg-6337ax
    '6307021xxx':
      ADMIN: sg-6541xx
      APP: sg-6541xx
      CHAT: sg-6541xx
      CMS: sg-6541xx
      DC: sg-6541xx
      GAME: sg-6541xx
      JS: sg-6541xx
      LOGAPI: sg-6541xx
      NAT: sg-6541xx
      NOSQL: sg-6541xx
      PROXY: sg-6541xx
      RDS: sg-6541xx
      REDIS: sg-6541xx
      SOGEI: sg-6541xx
      WEBRES: sg-6541xx
      WEB: sg-6541xx
      WHOS: sg-6541xx
    '843352xxxx':
      ADMIN: sg-9c823xx
      APP: sg-ee843x
      CHAT: sg-84833x
      CMS: sg-1a85336x
      DC: sg-b88533x
      GAME: sg-4f8ex
      JS: sg-8d843x
      LOGAPI: sg-xx823x
      NAT: sg-23803x
      NOSQL: sg-65823x
      PROXY: sg-0782x
      RDS: sg-eb8e3x
      REDIS: sg-e0833x
      SOGEI: sg-ed84x
      WEBRES: sg-ea8e3x
      WEB: sg-24803x
Resources:
  RDSSUBNETGROUP:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Private Subnet Group
      SubnetIds:
        - !FindInMap
          - AccountVariables
          - !Ref 'AWS::AccountId'
          - PrivateSubnetA
        - !FindInMap
          - AccountVariables
          - !Ref 'AWS::AccountId'
          - PrivateSubnetB
  RDS:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref InstanceType
      DBInstanceIdentifier: !Join
        - ''
        - - !Ref Country
          - !Ref InstanceName
          - c
          - !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - EnvironmentCode
          - '-01'
      DBSubnetGroupName: !Ref RDSSUBNETGROUP
      LicenseModel: !FindInMap
        - EngineToEngineType
        - !Ref Engine
        - License
      Engine: !FindInMap
        - EngineToEngineType
        - !Ref Engine
        - EngineType
      EngineVersion: !FindInMap
        - EngineToEngineType
        - !Ref Engine
        - EngineVersion
      MasterUsername: sqldba
      MasterUserPassword: !Ref AdministratorPassword
      PreferredMaintenanceWindow: 'mon:05:00-mon:06:00'
      PreferredBackupWindow: '04:00-05:00'
      PubliclyAccessible: false
      StorageType: gp2
      StorageEncrypted: true
      VPCSecurityGroups:
        - !FindInMap
          - AccountVariables
          - !Ref 'AWS::AccountId'
          - AdminSecurityGroup
        - !FindInMap
          - SecurityGroups
          - !Ref 'AWS::AccountId'
          - RDS
      Tags:
        - Key: Country
          Value: !Ref Country
        - Key: Environment
          Value: !FindInMap
            - AccountVariables
            - !Ref 'AWS::AccountId'
            - Environment
        - Key: Division
          Value: !Ref Division
        - Key: Team-Role
          Value: !Join
            - '-'
            - - !Ref Team
              - !Ref Role
        - Key: Source
          Value: Service Catalog
Outputs:
  RDSInstanceId:
    Value: !Ref RDS
  RDSEndpoint:
    Value: !GetAtt
      - RDS
      - Endpoint.Address
  RDSEndpointPort:
    Value: !GetAtt
      - RDS
      - Endpoint.Port
Rules: {}
