---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Terraform and Packer policies.
Parameters:
  Environment:
    Description: AWS Environment to be deployed to.
    Type: String
    AllowedValues:
    - PG
    - OPG
    - OPS
    - DV
    - ST
    - PR
Resources:
  CreateTerraPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join:
        - ''
        - - Ref: Environment
          - _International_Terraform_Infrastructure_Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Stmt7feedaa379a741d7b379eec1f14e69b1
          Action:
          - acm:ListCertificates
          - cloudfront:CreateCloudFrontOriginAccessIdentity
          - cloudfront:CreateDistributionWithTags
          - cloudfront:DeleteCloudFrontOriginAccessIdentity
          - cloudfront:DeleteDistribution
          - cloudfront:GetCloudFrontOriginAccessIdentity
          - cloudfront:GetDistribution
          - cloudfront:ListTagsForResource
          - cloudfront:UpdateDistribution
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:CreateSecurityGroup
          - ec2:DeleteSecurityGroup
          - ec2:DescribeAccountAttributes
          - ec2:DescribeImages
          - ec2:DescribeInstanceAttribute
          - ec2:DescribeInstances
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribeRegions
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSubnets
          - ec2:DescribeTags
          - ec2:DescribeVolumes
          - ec2:DescribeVpcAttribute
          - ec2:DescribeVpcs
          - ec2:ModifyNetworkInterfaceAttribute
          - ec2:RevokeSecurityGroupEgress
          - ec2:RunInstances
          - ec2:TerminateInstances
          - elasticache:CreateCacheCluster
          - elasticache:CreateCacheSubnetGroup
          - elasticache:DeleteCacheCluster
          - elasticache:DeleteCacheSubnetGroup
          - elasticache:DescribeCacheClusters
          - elasticache:DescribeCacheSubnetGroups
          - elasticache:ListTagsForResource
          - iam:AddRoleToInstanceProfile
          - iam:CreateInstanceProfile
          - iam:CreateRole
          - iam:DeleteInstanceProfile
          - iam:DeleteRole
          - iam:DeleteRolePolicy
          - iam:GetInstanceProfile
          - iam:GetRole
          - iam:GetRolePolicy
          - iam:GetUser
          - iam:DeleteRole
          - iam:CreatePolicy
          - iam:DeletePolicy
          - iam:AttachUserPolicy
          - iam:DetachUserPolicy
          - iam:ListInstanceProfilesForRole
          - iam:PutRolePolicy
          - iam:RemoveRoleFromInstanceProfile
          - rds:CreateDBInstance
          - rds:CreateDBSubnetGroup
          - rds:DeleteDBInstance
          - rds:DeleteDBSubnetGroup
          - rds:DescribeDBInstances
          - rds:DescribeDBSubnetGroups
          - rds:ListTagsForResource
          - route53:ChangeResourceRecordSets
          - route53:GetChange
          - route53:GetHostedZone
          - route53:ListHostedZones
          - route53:ListResourceRecordSets
          - s3:CreateBucket
          - s3:DeleteBucket
          - s3:DeleteBucketPolicy
          - s3:DeleteObject
          - s3:GetBucketCors
          - s3:GetBucketLocation
          - s3:GetBucketLogging
          - s3:GetBucketPolicy
          - s3:GetBucketRequestPayment
          - s3:GetBucketTagging
          - s3:GetBucketVersioning
          - s3:GetBucketWebsite
          - s3:GetLifecycleConfiguration
          - s3:GetObject
          - s3:GetObjectTagging
          - s3:GetReplicationConfiguration
          - s3:HeadBucket
          - s3:ListObjects
          - s3:PutBucketAcl
          - s3:PutBucketCors
          - s3:PutBucketPolicy
          - s3:PutBucketTagging
          - s3:PutLifecycleConfiguration
          - s3:PutObject
          - sts:AssumeRole
          - sts:GetCallerIdentity
          Effect: Allow
          Resource: "*"
        - Sid: Stmt4e4d8912a9d342e1aa97ff03b4611180
          Action:
          - s3:ListBucket
          Effect: Allow
          Resource: arn:aws:s3:::*
        - Sid: Stmt42b6f49f1dbb4123b7813c0065b44d3d
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          Effect: Allow
          Resource: arn:aws:s3:::*/*
